---
- hosts: debian
  remote_user: laurence
  tasks:
  - name: updates all debian package lists
    sudo: yes
    command: apt-get update
  - name: upgrade all debian packages
    sudo: yes
    command: apt-get upgrade
